version: 2
jobs:
  e2e_test:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/dev.txt" }}
            - v1-dependencies-
      - run:
          name: "install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/dev.txt" }}
      - run:
          name: "Start Django server"
          background: true
          command: |
            . venv/bin/activate
            make runserver
      - run:
          name: "run e2e_tests"
          command: |
            . venv/bin/activate
            make e2e_test

      - store_artifacts:
          path: test-reports
          destination: test-reports
  
  underlords_test:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/dev.txt" }}
            - v1-dependencies-
      - run:
          name: "install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/dev.txt" }}
      - run:
          name: "run underlords_tests"
          command: |
            . venv/bin/activate
            make underlords_test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  workflow:
    jobs:
      - e2e_test
      - underlords_test