requestBody:
  content:
    application/json:
      schema:
        required:
        - heroes
        type: object
        properties:
          heroes:
            type: array
            example: ["medusa","drow ranger","tidehunter","luna","chaos knight","omniknight","dragon knight","abbaddon","batrider","troll warlord"]
            items:
              type: string
responses:
  200:
    description: ok
    content:
      application/json:
        schema:
          type: object
          properties:
            heroes_per_tier:
              type: object
              properties:
                tier_1:
                  type: array
                  items:
                    type: string
                    example: "axe"
                tier_2:
                  type: array
                  items:
                    type: string
                    example: "juggernaut"
                tier_3:
                  type: array
                  items:
                    type: string
                    example: "lycan"
                tier_4:
                  type: array
                  items:
                    type: string
                    example: "mirana"
                tier_5:
                  type: array
                  items:
                    type: string
                    example: "techies"
            effects_per_alliance:
              type: object
              properties:
                assassin:
                  type: object
                  properties:
                    effect:
                      type: string
                      example: assassins gain a 10% chance to critical hit for 300% damage.
                    quantity:
                      type: integer
                      example: 3
                elusive:
                  type: object
                  properties:
                    effect:
                      type: string
                      example: elusive units gain +45% evasion.
                    quantity:
                      type: integer
                      example: 6