openapi: 3.0.1
info:
  title: Django API
  description: Sample Django + DRF project
  contact:
    email: "marco.barone.belo@gmail.com"
  version: 0.0.1
servers:
  - url: "http://localhost:8000/api"
tags:
  - name: Utilities
  - name: Underlords

paths:
  /healthcheck/:
    get:
      tags:
        - Utilities
      summary: Use it to check if the server is running
      $ref: "paths/healthcheck.yml"
  
  /heroes/:
    get:
      tags:
        - Underlords
      summary: List heroes names and tiers
      $ref: "paths/list_heroes.yml"
  
  /alliances/:
    get:
      tags:
        - Underlords
      summary: List alliances names
      $ref: "paths/list_alliances.yml"
  
  /build/:
    post:
      tags:
        - Underlords
      summary: Send your 10 heroes and get the heroes separated by tier and all alliances effects gained
      $ref: "paths/build.yml"
